name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test with Node.js v${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16', '18']
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies and run tests
        run: |
          npm run ci
        env:
          CI: true
